### ISSUE TITLE
requirements problem from PyPI

### ISSUE THREAD

**Issue by CatherineH** [Galvant/InstrumentKit#108]
I just tried installing InstrumentKit from pip, and I get this dependency problem:

```
Downloading/unpacking pyusb (from InstrumentKit)
  Could not find a version that satisfies the requirement pyusb (from InstrumentKit) (from versions: 1.0.0b1, 1.0.0b2, 1.0.0a3, 1.0.0rc1, 1.0.0a2, 1.0.0a3, 1.0.0a2)
```

Any ideas?

**Comment by scasagrande** [comment]
Python version?

**Comment by CatherineH** [comment]
3.4

**Comment by scasagrande** [comment]
I made new virtualenvs of both py2.7 and py3.5 and installed with the pip cache disabled, everything went fine. Maybe this is a Windows issue (assuming you're on your lab computer)?

**Comment by CatherineH** [comment]
It happened on both windows and linux...

**Comment by scasagrande** [comment]
Maybe you have some weird stuff cached in pip, make sure you don't have stuff already installed with `pip list`

Also try `pip install --no-cache-dir instrumentkit`

**Comment by scasagrande** [comment]
(I also just tried a new virtualenv with python 3.4, no problems)

**Comment by CatherineH** [comment]
hmm, okay, that worked.

**Comment by scasagrande** [comment]
![yay](https://media.giphy.com/media/msKNSs8rmJ5m/giphy.gif)
