### ISSUE TITLE
Termination strings should be able to handle multiple characters

### ISSUE THREAD

**Issue by scasagrande** [Galvant/InstrumentKit#117]
Some instruments like to use CRLF for their termination characters, usually on instruments where the devs have spent a little too much time using Windows. Right now most connections can only handle length 1 end-of-string characters, requiring you to terminate on the LF and then later cutting off the CR.

**Comment by CatherineH** [comment]
I just tested your latest commits to the toptica_test, and it works with all functionality.

**Comment by scasagrande** [comment]
I'm glad, but that doesn't have much to do with this issue :P

**Comment by scasagrande** [comment]
Merged into master with #146
