### ISSUE TITLE
Python 2.x/3.x single code base support

### ISSUE THREAD

**Issue by cgranade** [Galvant/InstrumentKit#14]
Following the advice on [Ondřej Čertík's blog](http://ondrejcertik.blogspot.ca/2013/08/how-to-support-both-python-2-and-3.html), migrating to a single code base for Python 2.x ≥ 2.6 and 3.x ≥ 3.3 may be a good path forward to an eventual Python 3 migration. To do so, we'll have to be consistent in our use of print functions, new-style classes, etc. Unicode literals will be in particular annoying, as most instruments accept only some subset of ASCII, such that we will have to be very careful to not let UTF-8 issues propagate all the way out to instruments.

**Comment by pumphaus** [comment]
Any news on this? Apparently the feature-py3 branch hasn't seen a commit in approx. one year.

**Comment by scasagrande** [comment]
Nope lol

And yes you're right, the branch is pretty stale. We *still* need to get a v1.0 done and publish to pypi. I think Py3 support should come after that. I also think that the feature is large enough that it should be broken down into smaller chunks.

**Comment by scasagrande** [comment]
Resolved with PR #93 :tada:
