### ISSUE TITLE
Inner vs. outer class consistency

### ISSUE THREAD

**Issue by cgranade** [Galvant/InstrumentKit#15]
Some of the classes here have enums and supporting classes as inner classes, while others have them as other classes in the same module. We should be consistent with this to minimize surprise to users. For instance, `NewportESP301` uses several classes in the root of `newportesp301.py` (https://github.com/Galvant/InstrumentKit/blob/dev/python/src/instruments/other/newportesp301.py), while newer classes have been written using more inner classes. The latter may be preferable to keep out `__init__.py` files and package namespaces clean.

**Comment by scasagrande** [comment]
Great thanks to @trappitsch for finishing an issue from 2013 😂

**Comment by trappitsch** [comment]
Less than a decade :)
