### ISSUE TITLE
Shebang Lines In Wrong Places

### ISSUE THREAD

**Issue by MichalKononenko** [Galvant/InstrumentKit#160]
If I understand correctly, the purpose of the ``#!`` line is to indicate that a particular python file is executable. However, these lines are scattered around library code, in places like [this](https://github.com/Galvant/InstrumentKit/blob/master/instruments/agilent/agilent33220a.py#L1). Are these files executable, or should the shebang line be removed?

**Comment by scasagrande** [comment]
You are technically correct, but I don't want to fix it.

**Comment by cgranade** [comment]
To expand a little bit, I agree if only because the shebang lines can help identify the script as Python at all to some editors which don't trust file extensions. There's no negative effect to "running" one of the internal modules, so it's likely fine to just keep them as is.
