### ISSUE TITLE
Serial Port Parameters

### ISSUE THREAD

**Issue by MichalKononenko** [Galvant/InstrumentKit#179]
I was working with a Lakeshore 475 over serial, and I couldn't get it working due to a mismatch between the required port parameters and IK's serial ports. Where can I set these parameters (data bits, stop bits, parity, etc.)

**Comment by scasagrande** [comment]
What does the 475 want for the correct settings?

**Comment by bilderbuchi** [comment]
Can you use the [`open_serial`](http://instrumentkit.readthedocs.io/en/latest/apiref/instrument.html#instruments.Instrument.open_serial) method to connect?
