### ISSUE TITLE
Interfacing Agilent 34401A

### ISSUE THREAD

**Issue by littlebrat** [Galvant/InstrumentKit#184]
I had to replace the terminator with '\r' in order to work with the same boilerplate class **Agilent34410a**. 
1. Why is this termination character different?
I am using the visa resource:
`instruments.agilent.Agilent34410a.open_visa('GPIB0::21::INSTR')`

2. Should I make a subclass that inherits **Agilent34410a** and just replace the termination character?

**Comment by scasagrande** [comment]
Your instrument may have its termination character changed from default. Or you can just update it at runtime after you instantiate your instrument:

```python
inst = instruments.agilent.Agilent34410a.open_visa('GPIB0::21::INSTR')
inst.terminator = "\r"
```

**Comment by scasagrande** [comment]
If it is actually a different default across all `34401A` vs `34410a`, and that is the only difference, then I suppose we should subclass it with just that terminator character being different.
