### ISSUE TITLE
Try to close socket

### ISSUE THREAD

**Issue by occoder** [Galvant/InstrumentKit#189]
But exception occurred prompting
"TypeError: shutdown() takes exactly one argument (0 given)"

**Comment by scasagrande** [comment]
Can you post the full stack trace please?

**Comment by occoder** [comment]
I was using a context manager to instantiate a socket object. Like
    def __enter__(self):
        self.ssm = ik.generic_scpi.SCPIInstrument.open_tcpip(self.host, self.port)
        self.ssm.terminator = "\r"
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.ssm._file.close()
 The __exit__ method calls the close() which triggered the exception.
File "C:\Users\www\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instruments\abstract_instruments\comm\socket_communicator.py", line 94, in close
    self._conn.shutdown()
TypeError: shutdown() takes exactly one argument (0 given)
Then I gave one parameter, i.e. socket.SHUT_RDWR, to it. The exception is gone.

**Comment by occoder** [comment]
And the context manager leads to another problem.
If I tried to reset the connection by using the instrument supported connection reset command within the context manager, the context manager never gets to the exit point.

**Comment by scasagrande** [comment]
Hmm, guess we're missing `socket.SHUT_RDWR`, good to know. I'll see about including that.

**Comment by scasagrande** [comment]
Fix has been merged in

Yes, it shouldn't have taken me this long.
