### ISSUE TITLE
is your project support tds754d or tds784d ?

### ISSUE THREAD

**Issue by youxiaojie** [Galvant/InstrumentKit#220]
is your project support tds754d or tds784d ?

**Comment by scasagrande** [comment]
It might work with some of the similar tektronix instrument drivers, but nothing specific for that! sorry!

**Comment by youxiaojie** [comment]
I mean to support tds754d, need I modify tektronix.py?
I found there is no 754D.

 Implemented from:
      | TDS Family Digitizing Oscilloscopes
      | (TDS 410A, 420A, 460A, 520A, 524A, 540A, 544A,
      | 620A, 640A, 644A, 684A, 744A & 784A)
