### ISSUE TITLE
pyvisa deprecation warning during test run

### ISSUE THREAD

**Issue by scasagrande** [Galvant/InstrumentKit#273]
Warning message is as follows:

FutureWarning: The visa module provided by PyVISA is being deprecated. You can replace `import visa` by `import pyvisa as visa` to achieve the same effect.

**Comment by trappitsch** [comment]
Saw that warning. Looks like it's just a potential naming conflict with [https://github.com/visa-sdk/visa-python](https://github.com/visa-sdk/visa-python). The `import pyvisa as visa` fix is thus probably okay, what do you think?

**Comment by bilderbuchi** [comment]
Indeed that `visa` package is the reason, we also hit this already and fixed it like [this](https://github.com/ralph-group/pymeasure/commit/c6c6ffa952425dbd75cbf41e7234210d6cc9076d).

**Comment by scasagrande** [comment]
Yeah I would just fully do the rename such that it is `import pyvisa` as its not like we have a ton of occurances of it.

**Comment by trappitsch** [comment]
For sure cleaner that way. I got some time to do that if you like, should be simple enough.

**Comment by scasagrande** [comment]
Sure go ahead. I'm updating the pint branch right now.

**Comment by scasagrande** [comment]
resolved
