### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by trappitsch** [Galvant/InstrumentKit#276]
As of last Oct 5 Python 3.9 is out (announcement [here](https://pythoninsider.blogspot.com/2020/10/python-390-is-now-available-and-you-can.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+PythonInsider+%28Python+Insider%29)). Local `tox` test w/ 3.9.0 w/ current master passes w/o any issues. To officially add support testing would have to be insured and added. 

Files that would need changes:

- [x] `tox.ini`
- [x] Readme
- [x] Travis - add to envs and set default to 3.9
- [x] `setup.py`

Comments? This is not very pressing, but might be good to be done eventually before the next release.

**Comment by scasagrande** [comment]
Yeah should be quick to add
