### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by trappitsch** [Galvant/InstrumentKit#326]
I briefly checked if we can simply extend to support Python 3.10. Setup already fails, the culprit is `ruamel.yaml~=0.15.37`. Removing version constraint and all tests pass. I guess we'd have to pin a new minimum version if 3.10 should be supported. Unfortunately, the place this package is used is in the `load_instrument` function in `config.py`, and that doesn't seem to be fully tested.

**Comment by scasagrande** [comment]
Looks like this version was set back when adding Py37 support https://github.com/Galvant/InstrumentKit/pull/195

Should be straight forward to fix this, even with the weaker test coverage
