### ISSUE TITLE
usbtmc comunication

### ISSUE THREAD

**Issue by njrebelo** [Galvant/InstrumentKit#332]
I have the VID and the PID of the equipment, its a PM100A, but can't communicate, with open_usb or open_usbtmc.

![image](https://user-images.githubusercontent.com/47528769/154966722-73048bea-ead1-4c66-819b-7ae72e52e876.png)

if I want to try VISA how do I find all the information I need?

**Comment by njrebelo** [comment]
I tried visa, but this happened:
![image](https://user-images.githubusercontent.com/47528769/154969399-78d06755-18c2-4e13-a9d8-6696625c4306.png)

But if I directly use the USBTMC library it works:
![image](https://user-images.githubusercontent.com/47528769/154969468-87287955-6d39-48bf-9082-5ff88bbfb7b8.png)

**Comment by njrebelo** [comment]
So now I manage to comunicate, but get an error when I try to read: 
![image](https://user-images.githubusercontent.com/47528769/154970731-eafab68b-d272-4490-9904-7bea0fd4e48b.png)

**Comment by trappitsch** [comment]
Might be that this is related to #260. We had a bug fix in there that should take some weird behavior out from this class. Could you try the latest version of `instrumentkit`? You can install it via:
```
pip install -U instrumentkit --pre
```
That should install `v1.0.0.dev0`, where this this is hopepfully fixed.

I'm not fully clear on why it doesn't work with `open_visa`, that would be the preferred method. Maybe worth trying again via visa after updating `ik`.

**Comment by njrebelo** [comment]
![image](https://user-images.githubusercontent.com/47528769/155988674-f82d5e11-2844-4d00-9db8-913f8c08043c.png)
Used PyVisa commandline to find the correct VISA code and now it worked perfectly

**Comment by scasagrande** [comment]
perfect!
