### ISSUE TITLE
Update setup.py, push to PyPI

### ISSUE THREAD

**Issue by cgranade** [Galvant/InstrumentKit#41]
To make things easier for users to install, we should post InstrumentKit to the Python Package Index. There's a nice [little tutorial](https://wiki.python.org/moin/CheeseShopTutorial) we can follow to make sure we have everything right. We just need to make sure we have the classifiers and requirements set right. The latter should be as is used by Travis, but it's still good to double-check.

**Comment by wil-langford** [comment]
Any word on the PyPI registration?

**Comment by scasagrande** [comment]
You're right, I need to get that finished. It's been a little hard the past few months for me to get this stuff done because of a variety of personal reasons. :/

**Comment by wil-langford** [comment]
I might be able to carve out a little time to look into it in the next few days.  If so, I'll try to get a pull request together.

**Comment by scasagrande** [comment]
I think we might *finally* be good to go for this. The plan is to, when I get an opportunity, to merge dev into master, and tag the commit `0.0.1`, and travis should take care of the rest.

Anyone notice anything I should do before the first pypi release?

**Comment by scasagrande** [comment]
Done! <3

**Comment by CatherineH** [comment]
![yay](http://i.imgur.com/0eKdIvZ.gif)
