### ISSUE TITLE
Support for Prologix GPIB-USB and GPIB-Ethernet Adapters

### ISSUE THREAD

**Issue by pumphaus** [Galvant/InstrumentKit#52]
Support for the [Prologix GPIB USB](http://prologix.biz/gpib-usb-controller.html)/[Ethernet Adapters ](http://prologix.biz/gpib-ethernet-controller.html) would be nice. I'm currently working on an implementation, but I'm unsure as to how to plug it into the existing API:
The method `open_gpibusb` hardcodes the Galvant USB Adapter. On Linux (and possibly OS X) some lookups in /sys/class/tty can reveal the manufacturer of the adapter and intelligently choose the correct backend, but I'm unsure if there exists a similar facility on Windows.
Worst case, a keyword argument or an entirely seperate method has to be added, I guess.

**Comment by scasagrande** [comment]
We could do something where an optional parameter is given to select the brand. Thankfully the protocol is very similar between the two. The main difference is the serial port settings. We could add another optional parameter to `serial_manager.new_serial_connection` for the flow control, and then modify `Instrument.open_gpibusb` to expose the baud and flow control parameters.

**Comment by glennlive** [comment]
What is the state of support for the Proligix devices?  Is there a development branch available publicly?

**Comment by scasagrande** [comment]
Development focus has been on many items lately, but Prologix adapters has not been on that list.

**Comment by pumphaus** [comment]
Since our project is built upon Python3 and back then InstrumentKit only supported Python2, I had stopped working on the Prologix support.
Now that Python3 support is there, I can look into it again. I don't know when I'll get to that, however.

**Comment by glennlive** [comment]
Did you have anything worth looking at, as I am considering using instrumentKit in my lab, but would need to add support for prologix, at least in a minimalistic fashion.

On Apr 16, 2016 12:05 PM, pumphaus <notifications@github.com> wrote:

Since our project is built upon Python3 and back then InstrumentKit only supported Python2, I had stopped working on the Prologix support.
Now that Python3 support is there, I can look into it again. I don't know when I'll get to that, however.

**Comment by scasagrande** [comment]
I'm curious, do the Prologix units actually use proper GPIB line drivers yet?

**Comment by glennlive** [comment]
The unit I have has been laying around the lab for >5 years now, so I can't speak to their new design having proper GPIB line drivers or not.  The one I have has the mega644 connected directly up to the 24-pin connector, without so much as a series resistor...  

That said, maybe the better question would, what is the preferred Ethernet based GPIB adapter to use with InstrumentKit?

**Comment by scasagrande** [comment]
@cgranade and I came up with the idea a few years ago to simply have a pass-through script running on a RPi. I still like that idea as it lets people "upgrade" their gpibusb or serialusb adapters to ethernet.

**Comment by cgranade** [comment]
Though I've not done so myself, it seems as though ``socat`` can be used to host serial connections via TCP. For security reasons I'd recommend tunneling such through SSH, to be sure.

**Comment by scasagrande** [comment]
Oh, this was added back in #221
